bocej/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('center/', include('center.urls')),
    path('ba/', include('bocej_aguipe.urls')),
]

bocej_aguipe/urls.py
from django.urls import path
from . import views

app_name = 'bocej_aguipe'

urlpatterns = [
    path('home', views.home, name='home'),
    path('add_center', views.add_center, name='add_center'),
]

center/urls.py
from django.urls import path
from . import views

app_name = 'center'

urlpatterns = [
    path('home', views.home, name='home'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

bocej_aguipe/models.py
from django.db import models

# Create your models here.

center/models.py
from django.db import models

class Center(models.Model):
    c_title = models.CharField('Nom du centre', max_length=200, null=True)
    c_address = models.CharField('Addresse', max_length=200, null=True)
    c_email = models.EmailField('Email', max_length=200, null=True)
    c_phone = models.CharField('Telephone', max_length=15, null=True)
    c_state = models.CharField('Etat', max_length=200, null=True)

    def __str__(self):
        return self.c_name
    class Meta:
        verbose_name_plural = 'CENTERS'

login/models.py
from django.db import models
from center.models import Center
from django.contrib.auth.models import User

class UserBA(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, verbose_name='Utilisateur', ) #username, email, password, activate, 
    full_name = models.CharField('Nom complet', max_length=250, null=True)
    phone = models.CharField('Telephone', max_length=15, null=True)
    type = models.CharField('Type (bocej/aguipe)', max_length=250, null=True) #bocej, aguipe
    role = models.CharField('Role (admin/simple_user)', max_length=250, null=True) #admin or simple_user
    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name_plural = 'USERS of BOCEJ-AGUIPE'

class UserCenter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, verbose_name='Utilisateur', ) #username, email, password, activate, 
    full_name = models.CharField('Nom complet', max_length=250, null=True)
    phone = models.CharField('Telephone', max_length=15, null=True)
    type = models.CharField('Type (center)', max_length=250, default='center', null=True) #center
    role = models.CharField('Role (admin/simple_user)', max_length=250, null=True) #admin or simple_user
    center = models.ForeignKey(Center, on_delete=models.CASCADE, null=True, verbose_name='Son Centre')
    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name_plural = 'USERS of CENTERS'

bocej_aguipe/forms.py
from django import forms
from center.models import Center
from login.models import UserCenter

class CenterForm(forms.ModelForm):
    c_title = forms.CharField()
    c_address = forms.CharField()
    c_email = forms.EmailField()
    c_phone = forms.CharField()

    c_title.widget.attrs.update(
        {'type': 'text', 'name': 'c_title', 'class': 'form-control', 'placeholder': "Titre du centre", 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )
    c_address.widget.attrs.update(
        {'type': 'text', 'name': 'c_address', 'class': 'form-control', 'placeholder': "Addresse (Ville, Quartier)", 'required': 'True'}
    )
    c_email.widget.attrs.update(
        {'type': 'email', 'name': 'c_email', 'class': 'form-control', 'placeholder': "Email du centre", 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )
    c_phone.widget.attrs.update(
        {'type': 'tel', 'name': 'c_phone', 'class': 'form-control', 'placeholder': "Numero de telephone du centre", 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )
    class Meta():
    	model = Center
    	fields = '__all__'
    
class  UserCenterForm(forms.ModelForm):
    full_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    phone = forms.CharField()
    full_name.widget.attrs.update(
        {'type': 'text', 'name': 'full_name', 'class': 'form-control', 'placeholder': "Nom & Prenom(s)", 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )
    username.widget.attrs.update(
        {'type': 'text', 'name': 'username', 'class': 'form-control', 'placeholder': "Nom d'utilisateur", 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )
    email.widget.attrs.update(
        {'type': 'email', 'name': 'email', 'class': 'form-control', 'placeholder': "Email", 'data-error': '*Veuillez renseigner ce champ.'}
    )
    password.widget.attrs.update(
    	{'type': 'password', 'name': 'password', 'class': 'form-control', 'placeholder': 'Mot de passe', 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )
    phone.widget.attrs.update(
    	{'type': 'tel', 'name': 'phone', 'class': 'form-control', 'placeholder': 'Numero de telephone du directeur', 'required': 'True', 'data-error': '*Veuillez renseigner ce champ.'}
    )

    class Meta():
    	model = UserCenter
    	fields = '__all__'
    

bocej_aguipe/views.py
from django.shortcuts import render
from login.models import UserBA
from center.models import Center
from bocej_aguipe.forms import *
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    user_profile = UserBA.objects.get(user=request.user)
    return render(request, 'bocej_aguipe/home.html', locals())

@login_required
def add_center(request):
    if request.method == 'POST':
        center_form = CenterForm(data=request.POST)
        if center_form.is_valid:
            center_form.save()

        username = request.POST['username']
        
        #user_center_form = UserCenter(user=user)
    else:
        center_form = CenterForm()
        user_center_form = UserCenterForm()

    return render(request, 'bocej_aguipe/add_center.html', locals())

center/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def home(request):
    return render(request, 'center/home.html', locals())

login/views.py
from django.shortcuts import render
from django.urls import reverse
from login.models import *
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse

def login(request):
    try_login = False
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            try:
                user_ba = UserBA.objects.get(user=user)
            except UserBA.DoesNotExist:
                user_center = UserCenter.objects.get(user=user)
                if user_center.type == 'center' and user_center.role == 'admin':
                    return HttpResponseRedirect(reverse('center:home'))  
            else:
                if (user_ba.type == 'bocej' or user_ba.type == 'aguipe') and user_ba.role == 'admin':
                    return HttpResponseRedirect(reverse('bocej_aguipe:home'))
        else:
            try_login = True
    
    return render(request, 'login/login.html', locals())

@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('login:login'))

bocej_aguipe/templates/bocej_aguipe/add_center.html
{% extends 'bocej_aguipe/_base.html' %}
{% load static %}
{% block title %}CREATION DE CENTRE{% endblock %}

{% block active-nav %}<br>
<ul id="mainnav-menu" class="list-group">
    <li>
        <a href="{% url 'bocej_aguipe:home' %}">
            <i class="demo-pli-home"></i>
            <span class="menu-title">Accueil</span>
        </a>
    </li>
    <li class="active-sub">
        <a href="#">
            <i class="ti-home"></i>
            <span class="menu-title">CENTRE</span>
            <i class="arrow"></i>
        </a>
        <!--Submenu-->
        <ul class="collapse in">
            <li class="active-link"><a href="{% url 'bocej_aguipe:add_center' %}">CREATION DE CENTRE</a></li>
            <li><a href="">LISTE DES CENTRES</a></li>
        </ul>
    </li>
    <li>
        <a href="#">
            <i class="demo-pli-file-html"></i>
            <span class="menu-title">EMAIL</span>
            <i class="arrow"></i>
        </a>
        <!--Submenu-->
        <ul class="collapse">
            <li><a href="">Blank Page</a></li>
        </ul>
    </li>  
</ul>
{% endblock %}    

{% block css %}
    <link href="{% static 'plugins/bootstrap-validator/bootstrapValidator.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-validator/bootstrapValidator.min.js' %}"></script>
    <script src="{% static 'plugins/masked-input/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'js/demo/form-validation.js' %}"></script>
{% endblock %}

{% block page-head %}{% endblock %}
    
{% block page-content %}
<br><br>
<div class="row">
    <div class="col-lg-2">&nbsp;</div>
    <div class="col-lg-8">
        <form id="demo-bv-accordion" class="form-horizontal bv-form" action="#" method="post" novalidate="novalidate"><button type="submit" class="bv-hidden-submit" style="display: none; width: 0px; height: 0px;"></button>
            <div id="demo-accordion" class="panel-group accordion">
                <div class="panel">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="text-center" data-parent="#demo-accordion" data-toggle="collapse" href="#demo-acc-panel-1">CREATION DU CENTRE</a>
                        </h4>
                    </div>
                    <div id="demo-acc-panel-1" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ center_form.c_title }}
                                    <small class="help-block">{{ center_form.c_title.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ center_form.c_address }}
                                    <small class="help-block">{{ center_form.c_address.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ center_form.c_email }}
                                    <small class="help-block">{{ center_form.c_email.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ center_form.c_phone }}
                                    <small class="help-block">{{ center_form.c_phone.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group" align="center">
                                    <a href="#demo-acc-panel-3" data-parent="#demo-accordion" data-toggle="collapse" class="btn btn-primary">Suivant</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="text-center" data-parent="#demo-accordion" data-toggle="collapse" href="#demo-acc-panel-3">CREATION DE L'ADMIN DU CENTRE</a>
                        </h4>
                    </div>
                    <div id="demo-acc-panel-3" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ user_center_form.full_name }}
                                    <small class="help-block">{{ user_center_form.full_name.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ user_center_form.username }}
                                    <small class="help-block">{{ user_center_form.username.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ user_center_form.email }}
                                    <small class="help-block">{{ user_center_form.email.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ user_center_form.password }}
                                    <small class="help-block">{{ user_center_form.password.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group has-feedback">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {{ user_center_form.phone }}
                                    <small class="help-block">{{ user_center_form.phone.errors }}</small>
                                </div>
                            </div>
                            <div class="form-group" align="center">
                                <button type="submit" class="btn btn-primary">Envoyer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg-2">&nbsp;</div>
</div>
{% endblock %}

bocej_aguipe/templates/bocej_aguipe/home.html
{% extends 'bocej_aguipe/_base.html' %}
{% block title %} AGUIPE | Accueil {% endblock %}

{% block active-nav %}
    <br>
    <ul id="mainnav-menu" class="list-group">
        <li class="active-link">
            <a href="{% url 'bocej_aguipe:home' %}">
                <i class="demo-pli-home"></i>
                <span class="menu-title">Accueil</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="demo-pli-home"></i>
                <span class="menu-title">CENTRE</span>
                <i class="arrow"></i>
            </a>
            <!--Submenu-->
            <ul class="collapse">
                <li><a href="{% url 'bocej_aguipe:add_center' %}">CREATION DE CENTRE</a></li>
                <li><a href="">LISTE DES CENTRES</a></li>
            </ul>
        </li>
        <li>
            <a href="#">
                <i class="demo-pli-file-html"></i>
                <span class="menu-title">EMAIL</span>
                <i class="arrow"></i>
            </a>
            <!--Submenu-->
            <ul class="collapse">
                <li><a href="">Blank Page</a></li>
            </ul>
        </li>  
    </ul>
{% endblock %}

{% block page-head %}{% endblock page-head %}

{% block page-content %}
    <hr class="new-section-sm bord-no">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-body text-center">
                <div class="panel-heading">
                    <h3>TABLEAU DE BORD</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="panel panel-purple panel-colorful">
                                <div class="pad-all text-center">
                                    <span class="text-3x text-thin">2</span>
                                    <p>CENTRES</p>
                                    <i class="demo-psi-receipt-4 icon-lg"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}    

center/templates/center/_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}CITC | Accueil{% endblock  %} </title>
    {% load static %}
    <link href="{% static 'bocej/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bocej/font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'bocej/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'bocej/css/style.css' %}" rel="stylesheet">
</head>

<body class="">
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <img alt="image" class="rounded-circle" src="{% static 'bocej/img/profile_small.jpg' %}"/>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="block m-t-xs font-bold"> {{ user.username|upper }} </span>
                                <span class="text-muted text-xs block"><b class="caret"></b></span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="dropdown-item" href="profile.html">Compte</a></li>
                                <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
                                <li><a class="dropdown-item" href="mailbox.html">MailBox</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'login:logout' %}">Deconnexion</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">CITC +</div>
                    </li>
                    <li><a href="{% url 'bocej_aguipe:home' %} "><i class="fa fa-th-large"></i>ACCUEIL</a></li>
                    <li><a href="{% url 'bocej_aguipe:home' %} "><i class="fa fa-bars"></i>CREER UN CENTRE</a></li>
                </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="search_results.html">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" placeholder="RECHERCHE" class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message"></span>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                            </a>
                            <ul class="dropdown-menu dropdown-messages">
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/a7.jpg">
                                        </a>
                                        <div class="media-body">
                                            <small class="float-right">46h ago</small>
                                            <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                            <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/a4.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="float-right text-navy">5h ago</small>
                                            <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                            <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/profile.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="float-right">23h ago</small>
                                            <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                            <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a href="mailbox.html" class="dropdown-item">
                                            <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'login:logout' %}">
                                <i class="fa fa-sign-out"></i> Deconnexion
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
                    <h2>This is main title</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="index.html">This is</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>Breadcrumb</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-sm-8">
                    <div class="title-action">
                        <a href="#" class="btn btn-primary">This is action area</a>
                    </div>
                </div>
            </div>

            <div class="wrapper wrapper-content">
                <div class="middle-box text-center animated fadeInRightBig">
                    <h3 class="font-bold">This is page content</h3>
                    <div class="error-desc">
                        You can create here any grid layout you want. And any variation layout you imagine:) Check out
                        main dashboard and other site. It use many different layout.
                        <br/>
                    </div>
                </div>
            </div>
            <div class="footer">
                <div align="center">
                    <strong>Copyright</strong> CITC &copy; 2020
                </div>
            </div>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'bocej/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'bocej/js/popper.min.js' %}"></script>
    <script src="{% static 'bocej/js/bootstrap.js' %}"></script>
    <script src="{% static 'bocej/js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'bocej/js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'bocej/js/inspinia.js' %}"></script>
    <script src="{% static 'bocej/js/plugins/pace/pace.min.js' %}"></script>
    {% block js %}{% endblock  %}
        
</body>
</html>

center/templates/center/home.html
{% extends 'center/_base.html' %}

login/templates/login/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <!--STYLESHEET-->
    <!--=================================================-->
    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="{% static 'css/nifty.min.css' %}" rel="stylesheet">
	<!--Pace - Page Load Progress Bar [OPTIONAL]-->
    <link href="{% static 'plugins/pace/pace.min.css' %}" rel="stylesheet">
	<script src="{% static 'plugins/pace/pace.min.js' %}"></script>
	<!--=================================================-->
	<link id="theme" href="{% static 'css/themes/type-full/theme-dark-full.min.css' %}" rel="stylesheet">
	<link href="{% static 'plugins/flag-icon-css/css/flag-icon.min.css' %}" rel="stylesheet">
</head>
<body>
    <div id="container" class="cls-container">		
		<!-- LOGIN FORM -->
		<!--===================================================-->
		<div class="cls-content">
			{% if try_login %}
				<div class="alert alert-purple">
					<button class="close" data-dismiss="alert"><i class="pci-cross pci-circle"></i></button>
					<strong>Erreur !</strong> Les données entrées sont erronées...
				</div>
			{% endif %}
		    <div class="cls-content-sm panel">
		        <div class="panel-body">
		            <div class="mar-ver pad-btm">
		                <h1 class="h3"><i class="flag-icon flag-icon-gn"></i>&nbsp;CONNEXION&nbsp;<i class="flag-icon flag-icon-gn"></i></h1>
					</div>				
		            <form action="{% url 'login:login' %}" method="POST">
						{% csrf_token %}
		                <div class="form-group">
		                    <input type="text" name="username" class="form-control" placeholder="NOM D'UTILISATEUR" autofocus>
		                </div>
		                <div class="form-group">
		                    <input type="password" name="password" class="form-control" placeholder="MOT DE PASSE">
						</div>
		                <button class="btn btn-primary btn-lg btn-block" type="submit">Connexion</button>
		            </form>
		        </div>
		        <div class="pad-all">
		            <a href="" class="btn-link mar-rgt">Mot de passe oublié ?</a>
		        </div>
		    </div>
		</div>
		<!--===================================================-->
    </div>
    <!--===================================================-->
    <!-- END OF CONTAINER -->

	<!--JAVASCRIPT-->
    <!--=================================================-->
    <!--jQuery [ REQUIRED ]-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!--BootstrapJS [ RECOMMENDED ]-->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--NiftyJS [ RECOMMENDED ]-->
    <script src="{% static 'js/nifty.min.js' %}"></script>
    <!--=================================================-->
</body>
</html>